# Generated by Django 3.1.4 on 2021-01-15 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210114_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='capitalization_period',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankdeposit',
            name='deposit_period',
            field=models.DurationField(default=datetime.timedelta(seconds=35)),
        ),
        migrations.AlterField(
            model_name='bankdeposit',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, default=0.314, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bankdeposit',
            name='last_capitalization',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankdeposit',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='sub_address',
            field=models.SlugField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='send_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
