# Generated by Django 3.1.4 on 2021-01-16 20:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_merge_20210116_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Wallet',
        ),
    ]
